/* Core Components*/
import {stringToFunction, GameObject} from './utils.js';
import {World} from './world.js';
import {GameEngine} from './game.js';
import {UserInterface} from './ui.js';

/* Load Custom Characters */

/* Load Custom Skills */
window.gamesettings = {
	difficulty: 0,
	framerate : 20
}
const GameInstance = {
	engine: null,
	ui: null,
	debug: {lastsecondframe: 0, lastsecondtime: 0},
	board: null,
	currentWorld: null
}

GameInstance.currentWorld = new World("Titan")
GameInstance.engine = new GameEngine()
GameInstance.ui = new UserInterface(GameInstance)

/*var boardOffset = UserInterface.eleByID("boardbackground").getBoundingClientRect()
document.addEventListener('mousemove', function(e) {
	GameInstance.ui.posSVG.x = Math.max(0, e.pageX - boardOffset.left)
	GameInstance.ui.posSVG.y = Math.max(0, e.pageY - boardOffset.top)
})*/

console.log(GameInstance.currentWorld)
console.log(GameInstance.engine)
console.log(GameInstance.ui)

function gameGELoop() {
	GameInstance.currentWorld.tick()
	GameInstance.engine.loop()
	window.setTimeout(gameGELoop, 1000 / window.gamesettings.framerate)
}
let gameUILoop = function () { 
	GameInstance.ui.loop(GameInstance.engine, GameInstance.currentWorld.dateFormat)
	if (GameInstance.ui.initialized === true) {
		UserInterface.updateTextByID("rangevalue",window.gamesettings.framerate)
		//UserInterface.updateTextByID("gamenginefps",GameInstance.engine.fps)
	}
}
function gameDebugLoop() {
	GameInstance.currentWorld.tick()
	GameInstance.engine.loop()
	window.setTimeout(gameDebugLoop, 1000)
}
let _gameGELoop = gameGELoop()
let _gameUILoopId = setInterval(gameUILoop, 1000 / 20)



GameInstance.engine.createCharacter("Hayennnnn",undefined,undefined,1)
GameInstance.engine.characters[0].stats.secondary.stamina.current = 10000
/* */
GameInstance.engine.createCharacter("Char101-mmmmmmmmmm")
GameInstance.engine.createCharacter("Char102")
GameInstance.engine.createCharacter("Char103")
GameInstance.engine.createCharacter("Char104")
GameInstance.engine.createCharacter("Char105")
GameInstance.engine.createCharacter("Char106")
GameInstance.engine.createCharacter("Char107")
GameInstance.engine.createCharacter("Char108")
GameInstance.engine.createCharacter("Char109")
GameInstance.engine.createCharacter("Char110")
GameInstance.engine.createCharacter("Char111")
GameInstance.engine.createCharacter("Char112")
GameInstance.engine.createCharacter("Char113")
GameInstance.engine.createCharacter("Char114")
GameInstance.engine.createCharacter("Char115")
GameInstance.engine.createCharacter("Char116")
GameInstance.engine.createCharacter("Char117")
GameInstance.engine.createCharacter("Char118")
GameInstance.engine.createCharacter("Char119")
GameInstance.engine.createCharacter("Char120")
GameInstance.engine.createCharacter("Char201")
GameInstance.engine.createCharacter("Char202")
GameInstance.engine.createCharacter("Char203")
GameInstance.engine.createCharacter("Char204")
GameInstance.engine.createCharacter("Char205")
/* * /
GameInstance.engine.createCharacter("Char206")
GameInstance.engine.createCharacter("Char207")
GameInstance.engine.createCharacter("Char208")
GameInstance.engine.createCharacter("Char209")
GameInstance.engine.createCharacter("Char210")
GameInstance.engine.createCharacter("Char211")
GameInstance.engine.createCharacter("Char212")
GameInstance.engine.createCharacter("Char213")
GameInstance.engine.createCharacter("Char214")
GameInstance.engine.createCharacter("Char215")
GameInstance.engine.createCharacter("Char216")
GameInstance.engine.createCharacter("Char217")
GameInstance.engine.createCharacter("Char218")
GameInstance.engine.createCharacter("Char219")
GameInstance.engine.createCharacter("Char220")
/* * /
GameInstance.engine.createCharacter("Char301")
GameInstance.engine.createCharacter("Char302")
GameInstance.engine.createCharacter("Char303")
GameInstance.engine.createCharacter("Char304")
GameInstance.engine.createCharacter("Char305")
GameInstance.engine.createCharacter("Char306")
GameInstance.engine.createCharacter("Char307")
GameInstance.engine.createCharacter("Char308")
GameInstance.engine.createCharacter("Char309")
GameInstance.engine.createCharacter("Char310")
GameInstance.engine.createCharacter("Char311")
GameInstance.engine.createCharacter("Char312")
GameInstance.engine.createCharacter("Char313")
GameInstance.engine.createCharacter("Char314")
GameInstance.engine.createCharacter("Char315")
GameInstance.engine.createCharacter("Char316")
GameInstance.engine.createCharacter("Char317")
GameInstance.engine.createCharacter("Char318")
GameInstance.engine.createCharacter("Char319")
GameInstance.engine.createCharacter("Char320")
/* * /
GameInstance.engine.createCharacter("Char401")
GameInstance.engine.createCharacter("Char402")
GameInstance.engine.createCharacter("Char403")
GameInstance.engine.createCharacter("Char404")
GameInstance.engine.createCharacter("Char405")
GameInstance.engine.createCharacter("Char406")
GameInstance.engine.createCharacter("Char407")
GameInstance.engine.createCharacter("Char408")
GameInstance.engine.createCharacter("Char409")
GameInstance.engine.createCharacter("Char410")
GameInstance.engine.createCharacter("Char411")
GameInstance.engine.createCharacter("Char412")
GameInstance.engine.createCharacter("Char413")
GameInstance.engine.createCharacter("Char414")
GameInstance.engine.createCharacter("Char415")
GameInstance.engine.createCharacter("Char416")
GameInstance.engine.createCharacter("Char417")
GameInstance.engine.createCharacter("Char418")
GameInstance.engine.createCharacter("Char419")
GameInstance.engine.createCharacter("Char420")
/* * /
GameInstance.engine.createCharacter("Char501")
GameInstance.engine.createCharacter("Char502")
GameInstance.engine.createCharacter("Char503")
GameInstance.engine.createCharacter("Char504")
GameInstance.engine.createCharacter("Char505")
GameInstance.engine.createCharacter("Char506")
GameInstance.engine.createCharacter("Char507")
GameInstance.engine.createCharacter("Char508")
GameInstance.engine.createCharacter("Char509")
GameInstance.engine.createCharacter("Char510")
GameInstance.engine.createCharacter("Char511")
GameInstance.engine.createCharacter("Char512")
GameInstance.engine.createCharacter("Char513")
GameInstance.engine.createCharacter("Char514")
GameInstance.engine.createCharacter("Char515")
GameInstance.engine.createCharacter("Char516")
GameInstance.engine.createCharacter("Char517")
GameInstance.engine.createCharacter("Char518")
GameInstance.engine.createCharacter("Char519")
GameInstance.engine.createCharacter("Char520")
/* * /
GameInstance.engine.createCharacter("Char601")
GameInstance.engine.createCharacter("Char602")
GameInstance.engine.createCharacter("Char603")
GameInstance.engine.createCharacter("Char604")
GameInstance.engine.createCharacter("Char605")
GameInstance.engine.createCharacter("Char606")
GameInstance.engine.createCharacter("Char607")
GameInstance.engine.createCharacter("Char608")
GameInstance.engine.createCharacter("Char609")
GameInstance.engine.createCharacter("Char610")
GameInstance.engine.createCharacter("Char611")
GameInstance.engine.createCharacter("Char612")
GameInstance.engine.createCharacter("Char613")
GameInstance.engine.createCharacter("Char614")
GameInstance.engine.createCharacter("Char615")
GameInstance.engine.createCharacter("Char616")
GameInstance.engine.createCharacter("Char617")
GameInstance.engine.createCharacter("Char618")
GameInstance.engine.createCharacter("Char619")
GameInstance.engine.createCharacter("Char620")
/* * /
GameInstance.engine.createCharacter("Char701")
GameInstance.engine.createCharacter("Char702")
GameInstance.engine.createCharacter("Char703")
GameInstance.engine.createCharacter("Char704")
GameInstance.engine.createCharacter("Char705")
GameInstance.engine.createCharacter("Char706")
GameInstance.engine.createCharacter("Char707")
GameInstance.engine.createCharacter("Char708")
GameInstance.engine.createCharacter("Char709")
GameInstance.engine.createCharacter("Char710")
GameInstance.engine.createCharacter("Char711")
GameInstance.engine.createCharacter("Char712")
GameInstance.engine.createCharacter("Char713")
GameInstance.engine.createCharacter("Char714")
GameInstance.engine.createCharacter("Char715")
GameInstance.engine.createCharacter("Char716")
GameInstance.engine.createCharacter("Char717")
GameInstance.engine.createCharacter("Char718")
GameInstance.engine.createCharacter("Char719")
GameInstance.engine.createCharacter("Char720")
/* * /
GameInstance.engine.createCharacter("Char801")
GameInstance.engine.createCharacter("Char802")
GameInstance.engine.createCharacter("Char803")
GameInstance.engine.createCharacter("Char804")
GameInstance.engine.createCharacter("Char805")
GameInstance.engine.createCharacter("Char806")
GameInstance.engine.createCharacter("Char807")
GameInstance.engine.createCharacter("Char808")
GameInstance.engine.createCharacter("Char809")
GameInstance.engine.createCharacter("Char810")
GameInstance.engine.createCharacter("Char811")
GameInstance.engine.createCharacter("Char812")
GameInstance.engine.createCharacter("Char813")
GameInstance.engine.createCharacter("Char814")
GameInstance.engine.createCharacter("Char815")
GameInstance.engine.createCharacter("Char816")
GameInstance.engine.createCharacter("Char817")
GameInstance.engine.createCharacter("Char818")
GameInstance.engine.createCharacter("Char819")
GameInstance.engine.createCharacter("Char820")
/* * /
GameInstance.engine.createCharacter("Char901")
GameInstance.engine.createCharacter("Char902")
GameInstance.engine.createCharacter("Char903")
GameInstance.engine.createCharacter("Char904")
GameInstance.engine.createCharacter("Char905")
GameInstance.engine.createCharacter("Char906")
GameInstance.engine.createCharacter("Char907")
GameInstance.engine.createCharacter("Char908")
GameInstance.engine.createCharacter("Char909")
GameInstance.engine.createCharacter("Char910")
GameInstance.engine.createCharacter("Char911")
GameInstance.engine.createCharacter("Char912")
GameInstance.engine.createCharacter("Char913")
GameInstance.engine.createCharacter("Char914")
GameInstance.engine.createCharacter("Char915")
GameInstance.engine.createCharacter("Char916")
GameInstance.engine.createCharacter("Char917")
GameInstance.engine.createCharacter("Char918")
GameInstance.engine.createCharacter("Char919")
GameInstance.engine.createCharacter("Char920")
/* */

console.log(GameInstance.engine.characters[0].getCharacterCurrentExpOfLevel())
console.log(GameInstance.engine.characters[0].getCharacterCurrentLevelTotalExp())